// Rewrite the instructions in your own words

// Write the objectives and the tests

// Write the pseudocode
/*

-create 2 variables and assign a value to them
-for variable 1 we assign rock scisor and paper
-for variable 2 we assign it to random choice between 1-3
-create a varibale to store the result.
- prompt the user to pick one "Rock, Paper or Scissors" choice.
- set if condition and compare if the enter number < , > = the random generated value
- print 
*/

// paste your JS generated by blockly below here
var player, random;

function mathRandomInt(a, b) {
  if (a > b) {
    // Swap a and b to ensure a is smaller.
    var c = a;
    a = b;
    b = c;
  }
  return Math.floor(Math.random() * (b - a + 1) + a);
}


player = window.prompt('pick one from 1 rock 2 paper 3 scissor');
random = mathRandomInt(1, 3);
if (player == random) {
  window.alert('tie');
}
if (player == 1) {
  if (random == 2) {
    window.alert('You lost');
  } else if (player == 1) {
    if (random == 3) {
      window.alert('You won');
    }
  }
}
if (player == 2) {
  if (random == 1) {
    window.alert('You won');
  } else if (player == 2) {
    if (random == 3) {
      window.alert('You lost');
    }
  }
}
if (player == 3) {
  if (random == 1) {
    window.alert('You lost');
  } else if (player == 3) {
    if (random == 2) {
      window.alert('You won');
    }
  }
}